image: ghcr.io/voluzi/cosmopilot
nodeUtilsImage: ghcr.io/voluzi/node-utils:2.9.0
cosmoGuardImage: ghcr.io/voluzi/cosmoguard:3.0.0
cosmoseedImage: ghcr.io/voluzi/cosmoseed:0.11.0
replicas: 1
imagePullSecrets: []
workerCount: 10
workerName: ""
webHooksEnabled: true
nodeSelector: {}
debugMode: false
probesEnabled: true
disruptionChecksEnabled: true

nodesPodPriority: 950
validatorPodPriority: 1050
defaultPriority: 0